language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  fqdn: tarkusetera.ee
  github_token: $TRAVIS_GIT_TOKEN
  keep_history: true
  on:
    branch: main